#!/usr/bin/env bash

COLOR_RED='\033[0;31m'
os=$(uname)
PROVIDER="heroku"
VERSION=$(go run ${PROVIDER}/version.go)
CURRENT_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ $CURRENT_GIT_BRANCH != 'master' ]; then
  printf "\n"
  printf "${COLOR_RED} Error: The build-release script must be run while on the master branch. \n ${COLOR_NONE}"
  printf "\n"

  exit 1
fi

echo "Pulling down latest from origin"
git pull origin master

echo "Switching to master branch"
git checkout master

echo "Checking if master branch is clean"
if [ "$(git status --porcelain)" != "" ]; then
  echo "branch is not clean. please add/commit or stage any changes first"
  exit 1
fi

echo "Checking if local & remote master branch are in sync"
if [ "$(git diff master origin/master)" != "" ]; then
  echo "Local and remote master branch are not in sync. Please rectify"
  exit 1
fi

echo "Checking if the tag already exists"
if git show ${VERSION} >> /dev/null 2>&1 || false ; then
  echo "tag ${VERSION} already exists. Did you forget to bump the version in version/version.go file?"
  exit 1
fi

echo "Creating new release tag ${VERSION}"
git tag -a "${VERSION}" -m "Release ${VERSION}"

echo "Pushing new release tag ${VERSION} to upstream origin"
git push origin "${VERSION}"